# Generated by Django 3.1.3 on 2020-11-04 22:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingrediente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32, unique=True)),
                ('unita_misura', models.CharField(max_length=16)),
                ('euro_kg', models.FloatField()),
                ('data_inserimento', models.DateTimeField(auto_now_add=True)),
                ('colore', models.CharField(blank=True, max_length=8)),
                ('note', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32, unique=True)),
                ('data_inizio', models.DateField()),
                ('data_inserimento', models.DateTimeField(auto_now_add=True)),
                ('colore', models.CharField(blank=True, max_length=8)),
                ('note', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Piatto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=32, unique=True)),
                ('url_ricetta', models.URLField(blank=True)),
                ('fascia_prezzo', models.CharField(choices=[('B', 'Basso'), ('M', 'Medio'), ('A', 'Alto')], max_length=1)),
                ('data_inserimento', models.DateTimeField(auto_now_add=True)),
                ('colore', models.CharField(blank=True, max_length=8)),
                ('note', models.CharField(blank=True, max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='PiattoMenu',
            fields=[
                ('id_piatto_menu', models.BigAutoField(primary_key=True, serialize=False)),
                ('data_pasto', models.DateField()),
                ('pranzo_cena', models.CharField(blank=True, choices=[('P', 'Pranzo'), ('C', 'Cena')], max_length=1)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.menu')),
                ('piatto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.piatto')),
            ],
        ),
        migrations.CreateModel(
            name='IngredientePiatto',
            fields=[
                ('id_ingrediente_piatto', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantita', models.FloatField()),
                ('ingrediente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.ingrediente')),
                ('piatto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='menu.piatto')),
            ],
        ),
        migrations.AddConstraint(
            model_name='piattomenu',
            constraint=models.UniqueConstraint(fields=('piatto', 'menu', 'data_pasto', 'pranzo_cena'), name='unique_piatto_menu'),
        ),
        migrations.AddConstraint(
            model_name='ingredientepiatto',
            constraint=models.UniqueConstraint(fields=('ingrediente', 'piatto'), name='unique_ingrediente_piatto'),
        ),
    ]
